# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015, 2016, 2017 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  postgresql: 9.4

notifications:
  email: false

sudo: false

services:
  - mysql
  - postgresql
  - rabbitmq

language: python

cache:
  - pip

env:
  - REQUIREMENTS=lowest EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_HOST=127.0.0.1 ES_VERSION=2.2.0
  - REQUIREMENTS=lowest EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_HOST=127.0.0.1 ES_VERSION=2.2.0
  - REQUIREMENTS=lowest EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_HOST=127.0.0.1 ES_VERSION=2.2.0
  - REQUIREMENTS=release EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_HOST=127.0.0.1 ES_VERSION=2.2.0
  - REQUIREMENTS=release EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_HOST=127.0.0.1 ES_VERSION=2.2.0
  - REQUIREMENTS=release EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_HOST=127.0.0.1 ES_VERSION=2.2.0 DEPLOY=true
  - REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_HOST=127.0.0.1 ES_VERSION=2.2.0
  - REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_HOST=127.0.0.1 ES_VERSION=2.2.0
  - REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_HOST=127.0.0.1 ES_VERSION=2.2.0

python:
  - "2.7"
  - "3.5"

matrix:
  fast_finish: true

before_install:
  - "nvm install 6; nvm use 6"
  - "mkdir /tmp/elasticsearch"
  - "wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio;' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: iL3rNkSvHzzd3it4PAMF0KO1WKDnRG3I9hyvjfRi+kgc5UNyUla749wXHGRM6Z2SKWSzxOM++8ke0n/ZHtdgmo/dNHxe1yZOEDykxvwgpvXNpicBpYmDm9WWh1ddV9dIYHbWnIDVSqCi3sa+U42wBhyT+LnEDy8pXUKn+M5zetCC6H6n13cxdsKpSKttiLP9lcNm2P9FP+tUsxnZGpdjmWJ4BL0VadxIYQoHd4t1y0due+G2a2DK3D67SviLWxfMM8dXugtvXXP05xFDxKvASJ6b0D3EAoIgja6TPV+riL9sKQdf4yf/VWcs+q4M6BHj1VDjsvRoO1JNNaB0H+gBatRbUHFOQhiZx8ljp7CB2myw2uSKr2gQ4nXuTDc+rsqGEE2elkfI5r8N/ZUrnvmounyEedruVjF9VEADrjt/1ZD+ILkm/W3yFJ6YFZ2HXWyoqnSobrFgIPyxSEC6OQOUdWAlPSIgts+BhqELRpDGrN6nD7OqgUFAqJqTK9lejqfZwL//kk0dlptHX6P7l4wwBygv9X/wuc19egOEX0E97j20G//WtwRjr3QLZb2pl/i5ReYVCzUTvBgzJp6Si3dmFGtyNMCkCy6Q+W8fuI6XKNDHzQuQWK02GA/XaLVaAclFzOHEeDKh1OnmJCl9xVerpCJ2PjMAN0EOmpe8HzuOamQ=
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    repo: inveniosoftware/invenio-oaiserver
    condition: $DEPLOY = true
